substitutions:
  friendly_name: "Entrance Roof"
  device_name: entrance-roof
  max_temp: "70" # °C
  dim_lenght: "3s"
  min_brightness: "470"
  max_brightness: "1000"
  leading_edge: "false"
  gamma_correct: "0"
  light_icon: mdi:coach-lamp

packages:
  dimmer: !include ../packages/shelly_dimmer_2.yaml