substitutions:
  friendly_name: "Livingroom Roof"
  device_name: livingroom-roof
  max_temp: "70" # °C
  dim_lenght: "5s"
  min_brightness: "200"
  max_brightness: "1000"
  leading_edge: "false"
  gamma_correct: "0"
  light_icon: mdi:coach-lamp

packages:
  dimmer: !include ../packages/shelly_dimmer_2.yaml

mqtt:
  broker: 192.168.10.207
  topic_prefix: shelly/${device_name}
  log_topic: shelly/${device_name}/log
  username: !secret mqtt_user
  password: !secret mqtt_password