
# Enable logging
logger:
  baud_rate: 0

time:
  - platform: homeassistant # Sync time with HA
    id: time_homeassistant
    timezone: "Europe/Oslo"
    on_time_sync:
      - component.update: sensor_uptime_timestamp

text_sensor:
  - platform: wifi_info # IP Address & SSID
    ip_address:
      name: "IP Address"
      icon: mdi:wifi
      entity_category: diagnostic

# Sensors with general information.
sensor:
  - platform: uptime # Uptime sensor (internal only).
    id: sensor_uptime
  - platform: template # Uptime timestamp
    id: sensor_uptime_timestamp
    name: "Uptime"
    device_class: "timestamp"
    accuracy_decimals: 0
    update_interval: never
    lambda: |-
      static float timestamp = (
        id(time_homeassistant).utcnow().timestamp - id(sensor_uptime).state
      );
      return timestamp;
    entity_category: diagnostic
  - platform: wifi_signal # WiFi Signal sensor.
    name: WiFi Signal
    icon: mdi:wifi-strength-2
    update_interval: 60s

button:
  - platform: restart # restart button
    name: "Restart"
    id: restart_button
  - platform: safe_mode # safe mode button
    name: "Safe Mode"
    entity_category: diagnostic